//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLyDuLich.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ChiTietHanhTrinh
    {
        public int IDChiTietHanhTrinh { get; set; }
        [Display(Name ="Mô tả")]
        public string moTa { get; set; }
        public Nullable<int> IDHanhTrinh { get; set; }
    
        public virtual HanhTrinh HanhTrinh { get; set; }
    }
}
