//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLyDuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDichVu
    {
        public int IDChiTietDichVu { get; set; }
        public string moTaDichVu { get; set; }
        public Nullable<int> IDDichVu { get; set; }
        public string tenChiTietDichVu { get; set; }
    
        public virtual DichVu DichVu { get; set; }
    }
}
