//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLyDuLich.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HanhTrinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HanhTrinh()
        {
            this.Tours = new HashSet<Tour>();
        }
    
        public int IDHanhTrinh { get; set; }
        [Display(Name = "Hành trình")]
        public string tenHanhTrinh { get; set; }
        [Display(Name = "Điểm khởi hành")]
        public string diemKhoiHanh { get; set; }
        [Display(Name = "Điểm kết thúc")]
        public string diemKetThuc { get; set; }
        [Display(Name = "Thời gian khởi hành")]
        public Nullable<System.DateTime> thoiGianKhoiHanh { get; set; }
        [Display(Name = "Thời gian kết thúc")]
        public Nullable<System.DateTime> thoiGianKetThuc { get; set; }
        [Display(Name = "Mô tả hành trình")]
        public string moTaHanhTrinh { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tour> Tours { get; set; }
    }
}
