//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLyDuLich.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.VeDatTours = new HashSet<VeDatTour>();
        }

        [Display(Name = "ID Khách hàng")]
        public int IDKhachHang { get; set; }
        [Required(ErrorMessage = "Họ tên không được bỏ trống !!!")]
        [Display(Name = "Họ tên")]
        public string hoTenKhachHang { get; set; }
        [Required(ErrorMessage = "Số điện thoại không được bỏ trống !!!")]
        [Display(Name = "Số điện thoại")]
        public string sdtKhachHang { get; set; }
        [Required(ErrorMessage = "Địa chỉ không được bỏ trống !!!")]
        [Display(Name = "Địa chỉ")]
        public string diaChi { get; set; }
        [Required(ErrorMessage = "CMND không được bỏ trống!!!")]
        [Display(Name = "CMND")]
        public string CMND { get; set; }
        public Nullable<int> IDTaiKhoan { get; set; }

        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VeDatTour> VeDatTours { get; set; }
    }
}
