//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLyDuLich.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhuyenMai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhuyenMai()
        {
            this.Tours = new HashSet<Tour>();
        }
    
        public int IDKhuyenMai { get; set; }
        [Display(Name ="Khuyến mãi")]
        public string tenKhuyenMai { get; set; }
        [Display(Name ="Điều kiện")]
        public string dieuKienKhuyenMai { get; set; }
        [Display(Name ="Thời gian")]
        public Nullable<System.DateTime> thoiGian { get; set; }
        [Display(Name ="Giá trị")]
        public Nullable<int> giaTriKhuyenMai { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tour> Tours { get; set; }
    }
}
