//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLyDuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int IDNhanVien { get; set; }
        public string hoTenNhanVien { get; set; }
        public string sdtNhanVien { get; set; }
        public string diaChi { get; set; }
        public string CMND { get; set; }
        public Nullable<int> IDChucVu { get; set; }
        public Nullable<int> IDTaiKhoan { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
