//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLyDuLich.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.HinhAnhs = new HashSet<HinhAnh>();
            this.VeDatTours = new HashSet<VeDatTour>();
            this.DichVus = new HashSet<DichVu>();
            this.HanhTrinhs = new HashSet<HanhTrinh>();
        }

        public int IDTour { get; set; }
        [Display(Name = "Tour")]
        public string tourName { get; set; }
        [Display(Name = "Giới thiệu tour")]
        public string tourDescription { get; set; }
        [Display(Name = "Số khách tối đa")]
        public Nullable<int> soLuongKhachToiDa { get; set; }
        [Display(Name = "Số khách hiện tại")]
        public Nullable<int> soLuongKhachHienTai { get; set; }
        [Display(Name = "Tình trạng tour")]
        public Nullable<bool> tinhTrangTour { get; set; }
        [Display(Name = "Khách sạn")]
        public Nullable<int> IDKhachSan { get; set; }
        [Display(Name = "Khuyến mãi")]
        public Nullable<int> IDKhuyenMai { get; set; }
        [Display(Name = "Giá")]
        public Nullable<int> gia { get; set; }
        [Display(Name = "Loại tour")]
        public Nullable<int> IDLoaiTour { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnh> HinhAnhs { get; set; }
        public virtual KhachSan KhachSan { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual LoaiTour LoaiTour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VeDatTour> VeDatTours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DichVu> DichVus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HanhTrinh> HanhTrinhs { get; set; }
    }
}
